<?php
// $customer = Mage::getSingleton('customer/session')->getCustomer();

// $product = Mage::getModel('catalog/product')->loadByAttribute('sku', '2072B');

// Fixed price products
$products = Mage::getModel('catalog/product')->getCollection()
              ->setStoreId(Mage::app()->getStore()->getId())
              ->addAttributeToFilter('attribute_set_id', ['eq' => '9'])
              ->addAttributeToFilter('status', ['eq' => '1'])
              ->addAttributeToSelect('*')
              ->load();

// echo count($products).'<br />'.'<br />';
// foreach ($products as $product) {
// 	var_dump($product->getName()).'<br />';
// }

?>

<h2>Current Special Price Products [Special] (<?php echo count($products); ?> items)</h2>
<h4 class="red">Select Attribute Set is Special [attribute_set_id=9] (* Just Change Attribute Set)</h4>
<div class="clearfix">
	<div class="grid spe-item left">
		<table style="border-spacing: 0;">
			<thead>
				<tr style="font-weight: 700;">
					<td>ID</td>
					<td>Sku</td>
					<td>Sales Type</td>
					<td>Product Type</td>
					<td>Price</td>
					<td>Special Price</td>
					<td>Switch to [Default]</td>
				</tr>
			</thead>
			<tbody>
				<?php $ii = 1; foreach ($products as $product): ?>
					<tr class="pointer <?php if($ii%2 > 0) echo 'even'; ?>">
						<td><?php echo sprintf('%03d', $ii++).' - '.$product->getId() ?></td>
						<td><?php echo $product->getSku() ?></td>
						<td>
							<?php 
								$categories = $product->getCategoryIds();
								$sales_type = 'Other';
								if (in_array(5, $categories)) {
									$sales_type = 'Pre-Order';
								} elseif (in_array(110, $categories)) {
									$sales_type = 'Special Price Item';
								} elseif (in_array(111, $categories)) {
									$sales_type = 'New Release Item';
								}
								echo $sales_type;
							?>
						</td>
						<td><?php echo $product->getTypeId() ?></td>
						<td><?php echo $product->getPrice() ?></td>
						<td><?php echo $product->getSpecialPrice() ?></td>
						<td><div class="btn-set"><a href="#switch" class="btn-submit">Switch</a></div></td>
						<input type="hidden" name="product_sku" id="product_sku" value="<?php echo $product->getSku() ?>" >
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="spe-item right ">
		<h4>Add Special Price Product</h4>
		<div>
			<form action="/" class="form-holder">
				<input type="hidden" name="_token" value="<?php echo time(); ?>">
				<input type="text" name="id" style="display: none;">
				<div class="entry-form">
					<label for="product_sku">Sku</label>
					<input type="text" name="product_sku" id="product_sku" >
				</div>
				<div class="btn-set">
					<a href="#add" class="btn button btn-submit">Submit</a>					
				</div>
			</form>
		</div>
	</div>
</div>